
stages:
  - setup
  - compile
  - offlineProduction
  - analysis
  
setup:
    image: $CI_REGISTRY_IMAGE
    stage: compile
    rules:
        - if: $CI_PIPELINE_SOURCE != "schedule"
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    script:
        - echo $Starting tests
        - which root
        - git submodule add ../MilliDAQ.git
        - cd MilliDAQ/
        - make clean && make shared
        - cd ../
        - cd Run3Detector
        - sed -i '/thisroot.sh/d' setup.sh
        - sed -i "s|/homes/milliqan/MilliDAQ|$PWD/../MilliDAQ|g" setup.sh
        - sed -i "s|UCSB|GitLab|g" setup.sh
        - sed -i 's/\.\.\///' setup.sh
        - . setup.sh
        - curl -o input.root https://cernbox.cern.ch/s/4b3s7iRaaP2cVnj/download
        - ./compile.sh test.exe

offlineProduction:
    image: $CI_REGISTRY_IMAGE
    stage: offlineProduction
    rules:
        - if: $CI_PIPELINE_SOURCE != "schedule"
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    script:  
        - cd Run3Detector
        - python3 scripts/runOfflineFactory.py --inputFile input.root --outputFile output.root --exe ./test.exe

analysis:
    image: $CI_REGISTRY_IMAGE
    stage: analysis
    rules:
        - if: $CI_PIPELINE_SOURCE != "schedule"
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    script:  
        - echo "Put analysis here!"
        - which root
        - pip list

build image:
    image: carriganm95/milliqan_uproot:latest
    stage: setup
    tags:
        #- docker-privileged
    services:
        - name: docker:dind
    rules:
        - if: $CI_PIPELINE_SOURCE == "schedule"
    variables:
        DOCKER_HOST: tcp://docker:2375/
        DOCKER_DRIVER: overlay2
        DOCKER_TLS_CERTDIR: ""
    script:
        - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
        - docker build -t $CI_REGISTRY_IMAGE .
        - docker push $CI_REGISTRY_IMAGE
        
